[package]
name = "fcitx5-fep-rust"
version = "0.1.0"
edition = "2018" # Explicitly using 2018 edition

[dependencies]
# No external dependencies for now, as requested.
# For a real implementation, you would likely need:
# dbus = "0.9" # Or zbus = "3"
# libc = "0.2"
# atty = "0.2" # Optional: for checking if running in a TTY
